##
## Build
##

FROM golang:1.19.5-bullseye AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /razorblade cmd/shortener/main.go

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /razorblade /razorblade

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/razorblade"]
